ProtoSchool/protoschool.github.io

src/components/lessons/boiler.vue

Without `:validate="validate"` in `<Lesson>` things would fail if
you want to have a validation function.

Add validation atttibute to boilerplate

---

src/App.vue
src/components/Button.vue
src/components/Lesson.vue
src/main.js

WIP on #15 
**Initial**
**oh noes**
**YASSSSSS QUEEEEN**
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

feat: lovely lesson layout

---

src/components/Lesson.vue
src/lessons/Basics/01.vue
src/lessons/Basics/02.vue
src/lessons/Basics/03.vue
src/lessons/Blog/01.vue
src/lessons/Blog/02.vue
src/lessons/Blog/03-exercise.md
src/lessons/Blog/03.vue
src/lessons/Blog/04.vue
src/lessons/Blog/05.vue
src/lessons/Blog/06.vue
src/lessons/Blog/07.vue

Added a message to the bottom of the lesson template that encourages users to submit their questions/feedback on the lesson, linking to a new issue with the lesson number / title / path pre-filled and a body that explains the type of feedback we'd appreciate. 
Addresses issues #45 and #42.

Question link

---

src/components/Lesson.vue
src/components/home/ExerciseLink.vue
src/components/home/Home.vue
src/components/home/ipfs.svg
src/lessons/Basics/01.vue
src/lessons/Basics/02.vue
src/lessons/Basics/03.md
src/lessons/Basics/03.vue
src/lessons/Blog/01.md
src/lessons/Blog/01.vue
src/lessons/Blog/02.md
src/lessons/Blog/02.vue
src/lessons/Blog/03-exercise.md
src/lessons/Blog/03.vue
src/lessons/Blog/04.vue
src/lessons/Blog/05.vue
src/lessons/Blog/06.md
src/lessons/Blog/06.vue
src/lessons/Blog/07.vue

This PR should fully address: 
- Issue #67 by changing references to IPLD to IPFS, including logos
- Issue #69 by labelling each subset of a workshop a "lesson" and removing exercise numbers, as well as creating what I hope are more compelling and descriptive lesson titles
This needs a thorough review from @mikeal to ensure the direct replacements of IPLD with IPFS are acceptable as is without any additional rewording. Note that I did _not_ edit the references to "IPLD Explorer." 
I'm very open to feedback from @mikeal @vmx et al on the new proposals for lesson titles.

Rename lessons & change IPLD mentions to IPFS

---

README.md
src/components/Lesson.vue
src/lessons/Basics/03.vue
src/lessons/Blog/07.vue
src/lessons/boiler.vue
src/main.js

Closes #62 and closes #70 by programmatically interpreting the route path to determine the shortname of the workshop ("Basics" or "Blog"), the lesson number, and the total number of lessons in the current workshop, without the author of a new workshop having to add this info explicitly. This also removes the need for the author to add a "last: true" property to make the button on the final lesson of the series work properly. 
Note that the current solution will only work if we stick with our current pattern for paths (eg "/basics/02"), picking one-word shortnames for workshops. If we need to deviate from this pattern down the road, the "workshopShortname" calculated value will need to be adjusted, but this could be done without much difficulty if we consistently use hyphens or something …

Calculate/display workshop, lesson #, lesson total

---

src/components/home/ExerciseLink.vue
src/components/home/Home.vue

Closes #77 by preventing lesson titles from wrapping to under lesson numbers at narrower screen widths. 
Previous state: 
New state: 
@mikeal @olizilla When testing, please adjust your screen width and ensure that the green "LESSON X" never wraps its numeral down to a second line. Only the text titles should wrap.
Note that I also changed the point at which the illustrations to the right of the lesson lists disappear, since they were limiting the space available at medium window widths.

Fix wrapping of lesson titles on homepage

---

src/components/Lesson.vue

- Update conditional for "More tutorials" button so that when you click
to "Reset code" the button will return to the "Submit" state and stay
that way until correct code is submitted again.
- Previously the code allowed the button to appear as "More Tutorials"
if `output.test.success` were still true. Now `lessonPassed` must always
be true, as that field is updated to be false when you reset the code.

Repair reset from "More tutorials" to "Submit" btn - closes #118

---

src/lessons/Blog/06.vue

- Make 'prev: null' a valid option for the treePostCid (previously
treePostCid could not have a 'prev' field at all)

Make 'prev: null' valid for treePostCid (fixes #43)

---

LICENSE.md
README.md
package.json

Partially addresses #130, although we may need to apply licenses to other repos as well. 
@mikeal I'm not at all positive I've correctly interpreted your suggestion in #130. 
I don't know how "There's no CLA or copyright assignment as part of the contribution process." fits into what we add to our page, or how it fits with the fact that both of the proposed licenses include a place for a copyright assignment.
I've filled in the copyright assignment in the licenses as Protocol Labs. Is this correct, and is it right that it's 2019 (should it be 2018-2019 based on when work started)? 
I"ll get your feedback on this PR first before trying to apply a license to other repos. Do we need one on the organizing repo and the individual chapter repos as well?

Add license 

---

src/components/chapters/chapters.json

- Use 2-digit country codes for consistency as specified in chapter
setup instructions

Use 2-digit country codes

---

package-lock.json
package.json
src/components/Lesson.vue
vue.config.js

- alias the ipfs dependency to the pre-built bundle.
- update link to explore.ipld.io
- update ipfs to latest release
This ensures the browser friendly ipfs bundle is used. Before this
PR we were seeing a bunch of errors when IPFS tried to init, which
are caused by trying to get webpack to bundle the node build and
not substituting all the browser friendly deps correctly. Luckily,
this work is done for us in the ipfs dist build, so just use that.
fixes #164
fixes #125
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

fix: ensure ipfs browser bundle is used

---

public/index.html

Hopefully avoids showing the `<noscript>` tag when googling for protoschool:

Add meta description tag to improve display in search results

---

src/components/Lesson.vue

- Rename `workshopMenu` to `tutorialMenu`
- Update "More Tutorials" buttons to link to "/tutorials/" instead of "/"
via tutorialMenu function

Correct link target for "More Tutorials" button

---

.github/main.workflow

Build the project then pins the `dist` dir on https://cluster.ipfs.io
An IPFS status will be added to the latest commit in a PR and show up in the status checks box at the bottom as a link to the build out preview on cluster.
fixes #190

feat: IPFS preview on PR via github action

---

public/index.html

This implements the IPFS Camp ribbon banner 💅
Currently only visible on larger screen layouts however I may also add a smaller screen variant once I've had chance to evaluate the analytics.
ref: protocol/2019-ipfs-camp#13

feat: include ipfs-camp ribbon

---

.travis.yml

Removes `npm run test` as we don't have any test for now and was breaking the CI for the lack of `-` when running multiple scripts.

fix: travis config

---

README.md
src/components/Lesson.vue
src/tutorials/Basics/01.vue
src/tutorials/Basics/02-exercise.md
src/tutorials/Basics/02.vue
src/tutorials/Basics/03.vue
src/tutorials/Blog/01.vue
src/tutorials/Blog/02-exercise.md
src/tutorials/Blog/02.vue
src/tutorials/Blog/03.vue
src/tutorials/Blog/04.vue
src/tutorials/Blog/05.vue
src/tutorials/Blog/06.vue
src/tutorials/Blog/07.vue

Closes https://github.com/ProtoSchool/protoschool.github.io/issues/89.

feat: add ability to view solutions in lessons

---

src/components/Lesson.vue

With the lib we're using to render the monaco editor we can't open a new tab nor have a [diff editor](https://microsoft.github.io/monaco-editor/playground.html#creating-the-diffeditor-multi-line-example) (this would be the nicer solution IMO).
I've been looking for other vue monaco lib but haven't found any that supports that.
So, another approach I thought about was to toggle another editor (read only) with the solution:
There are two problems that can arise: 
- When there's a lot of code in the editor, you'll have to scroll down to view the solution (to overcome this we can automatically scroll to the solution code when pressing the `View Solution` button);
- It may not be clear to the user what gets submitted when you press the `Submit` button;
<hr />
Closes …

fix: preserve user code when viewing solution

---

README.md
src/components/Lesson.vue
src/components/LessonLink.vue

While testing with a screen reader I discovered that 
- our usage of symbols for complete / in progress / not yet started status in the lesson listings are very cool when read by a screen reader! 
- our "in progress" label had "complete" as its alt tag :(
This PR fixes the alt tags and also fixes some relative path mistakes in the readme.

Fix alt tag

---

README.md
src/components/Lesson.vue
src/tutorials/Basics/01.vue
src/tutorials/Basics/02.vue
src/tutorials/Basics/03.vue
src/tutorials/Blog/01.vue
src/tutorials/Blog/02.vue
src/tutorials/Blog/03.vue
src/tutorials/Blog/04.vue
src/tutorials/Blog/05.vue
src/tutorials/Blog/06.vue
src/tutorials/Blog/07.vue

Add markdown support for both the success and fail messages, so you can do whatever:
| old | crazy stuff you can do now |
| --- | --- |
| <img width="720" alt="a" src="https://user-images.githubusercontent.com/33324750/57522177-e7180b00-7319-11e9-9dee-84b97f669f40.png"> | <img width="721" alt="c" src="https://user-images.githubusercontent.com/33324750/57522712-d7e58d00-731a-11e9-8f08-7a6dd0b23688.png"> |

feat: add markdown to outputs

---

README.md

I did this using the package @olizilla suggested (https://github.com/jonschlinkert/markdown-toc) but haven't pushed the changes to package.json or package-lock.json, just pasted in the results from the CLI command `markdown-toc --no-firsth1 README.md`.
Is there a reason to upload those, like building a function that keeps the ToC up to date by itself each time we make changes, or shall I go ahead and merge as is and continue using the CLI which I've installed globally to make updates?

Add ToC to readme

---

src/components/Lesson.vue

Reposition the `Useful Concepts` box as it was taking a lot of horizontal space from the lesson:
| old | new |
| --- | --- |
| <img width="880" alt="old" src="https://user-images.githubusercontent.com/33324750/57690231-163fbc80-7639-11e9-8178-b617ed7dd331.png"> | <img width="867" alt="new" src="https://user-images.githubusercontent.com/33324750/57690229-15a72600-7639-11e9-89e3-0e522b88dfa2.png"> |

chore: update useful concepts positioning

---

package-lock.json
package.json
src/tutorials/Basics/01.vue
src/tutorials/Basics/02.vue
src/tutorials/Blog/01.vue
src/tutorials/Blog/02.vue
src/tutorials/Blog/03.vue
src/tutorials/Blog/04.vue
src/tutorials/Blog/05.vue
src/tutorials/Blog/06.vue
src/tutorials/Blog/07.vue
vue.config.js

- Update to the latest version of IPFS
- Update the hashes to base32 to pass validations
- Remove unneeded webpack configs

chore: update ipfs

---

src/App.vue
src/components/Lesson.vue

Make the page full height when there is no content.
Deleted some stuff for this screenshot just to prove that it works:
Fixes https://github.com/ProtoSchool/protoschool.github.io/issues/255.

fix: full height page

---

public/index.html
src/main.js

This PR adds tracking via Countly (hosted at countly.ipfs.io) while respecting "do not track" requests in the user agent. 
It taps into Vue's routing system to allow us to see the path for any resource that has its own path, such as tutorial landing pages and individual lessons: 
This PR also removes tracking via Google Analytics. (Will this cause any problems for you, @mikeal?)
This PR does not address event tracking, such as clicks on "reset code," "view solution," or "submit" buttons within lessons. We'll plan to address that in a second PR once this is in place. 
Note: If testing on localhost, you'll need to comment out line 70 in `index.html` (which restricts tracking to views of the live website) and uncomment line 65 (which tracks views on localhost as well).
Pair programmed by …

Add analytics w/ page views via Countly 

---

src/components/Tutorial.vue

Guarantees identical width between tutorial components in the Tutorials page.
Fixes #295

fix: fix layout of tutorials in tutorials page

---

src/static/tutorials.json
src/tutorials/0005/01.md
src/tutorials/0005/02.md
src/tutorials/0005/03.md
src/tutorials/0005/04.md
src/tutorials/0005/05.md
src/tutorials/0005/06.md

I pulled a branch from @dominguesgm's work in order to encapsulate all of my editorial thoughts. Hopefully this tack doesn't complicate things too much. Note that i interjected some asides here and there, eg when i wasn't clear on the intent of a phrase or sentence. I'll extract those once resolved.
My hidden agenda with all of the protoschool material i attempt to edit is to **learn**, and i'm happy to say that this experience was educational (as always). So thanks for helping me learn something new!

Er suggestions nonmfs

---

src/utils/paths.js

Currently the path is used to derive the shortname of a tutorial by splitting it apart into words and capitalizing the first letter of each of them, so for example 
`https://proto.school/#/data-structures` => `Data Structures`
I noticed while proofing the upcoming Files API tutorial that it's printing as `Files Api`, which is less impressive.  This small tweak will allow case-by-case override when we encounter a word that our default casing won't work on. The tweak for `api` => `API` is included in this PR, but to test this PR against the `code` branch you'll need to temporarily adjust the `correctedCases` object in `src/utils/paths.js` to include an example you can already view, for example:  
```javascript
const correctedCases = {
api: 'API',
structures: 'STruCTures',
mutable: 'MUTable' …
```

Fix: allow casing override

---

src/components/Output.vue

Closes #299 
Partially addresses some of the suggestions for use of IPFS Camp content identified in #261, partially addressing epic #307.
When the result of a code challenge is a CID, a link to "View in CID Inspector" (which goes to a pre-filled URL in https://cid.ipfs.io/) now appears alongside the link to "View in IPLD Explorer."
I'd love feedback on the ideal layout since both options would always be present at the same time. Current state of wrapping shown below, although few people will be attempting to code on narrower screens.

Add link to CID inspector when result is CID

---

src/static/tutorials.json

- Add video from core course A to multiple resources pages
- Push docs to the top of each resources list
- Add some additional cross-linking between existing tutorials
Partially addresses some of the suggestions for use of IPFS Camp content identified in #261, partially addressing epic #307.

Update resources pages with IPFS Camp Core Course A

---

src/main.js

Currently this [link](https://proto.school/#/mutable-file-system/11) on ProtoSchool goes to a 404 page. This patch (I'm assuming) fixes that.

Fix link to mutable-file-system tutorial Lesson 11

---

cypress/integration/tutorials.spec.js
src/components/Navigation.vue
src/components/Resources.vue
src/components/Tutorial.vue
src/components/Validator.vue

A new Cypress test loops through all tutorials in `tutorials.json` and ensures that each individual lesson and resources page is listed on the tutorial page and is able to render. This will prevent further errors with routes as recently discovered and fixed in #325 and noted in [this comment](https://github.com/ProtoSchool/protoschool.github.io/issues/323#issuecomment-562629335) on issue #323 (raised by @dominguesgm). This new test is run on every tutorial and lesson (including resources pages) regardless of lesson type.
The existing test built by @olizilla to check that all solution code actually passes validation has been updated slightly to: 
- reflect our new mandatory status for resources pages
- allow simpler updates for which tutorials should have this test run (just add their IDs …

Add rendering tests

---

src/components/Explorer.vue
src/components/Output.vue
src/tutorials/0002/01.vue
src/tutorials/0002/02.vue
src/tutorials/0003/01.vue
src/tutorials/0003/02.md
src/tutorials/0003/02.vue
src/tutorials/0003/03.vue
src/tutorials/0003/04.vue
src/tutorials/0003/05.vue
src/tutorials/0003/06.vue
src/tutorials/0003/07.vue

@mikeal this is a first stab at a fix to the issue @lanzafame raised in #120 where we were printing CID objects instead of just CID strings. 
This works and displays both CIDs as strings in the output when they don't match, but in order to make it recognize a correct answer in this approach I had to switch to loose equality to make the result (a CID which comes as an object) match the correct CID (expressed as a string). Is it safe to do it this way or would you recommend some kind of actual conversion? 
I'll circle around and look for other cases of this problem to fix after confirming whether this approach feels reasonable.

Display CID strings, not objects

---

src/components/Resources.vue
src/static/tutorials.json

Closes #333 by adding a link to the video from IPFS Camp Core Course D (Lifecycle of Data in the DWeb) to all existing resources pages, with slightly different descriptions depending what the user has already learned. 
Also adds markdown functionality for resource descriptions by importing `marked`. Because the text now pulls in as inner HTML, as a child of the div we created directly, I found I need to create a new custom class to adjust the spacing on the `p` element that pulls in (to keep the description directly under the resource title). As far as I know I can't use Tachyons directly to affect the child of the element I have access to.

Add video from IPFS Camp Core Course D to resources pages

---

CODE_OF_CONDUCT.md

Just realized GitHub was looking at this repo and thinking we had no CoC because it's only on the organizing repo and our chapter repos. Fixing that!

Copy Code of Conduct from organizing repo

---

src/components/Button.vue
src/components/Validator.vue

Updated disabled button styles to match @ericronne's recommendation in #317.
One thing to note is that as the button is disabled in the loading state, it will show up with the new disabled style. We need to discuss whether this is appropriate or not @terichadbourne @zebateira.

chore: improved button disabled status

---

src/tutorials/0005/05.vue

Before this patch, the exercise would fail - even with the solution code - when only one file was uploaded, as the `resultingFiles.length` wasn't guarded by `resultingFiles.length !== uploadedFiles.length`.
To reproduce:
(1) upload one file
(2) copy solution code
(3) click "Submit"

Tutorial 5, Lesson 5 exercise validation fix

---

src/tutorials/0005/07.md

This seemingly innocent newline makes sure the code block renders correctly.
The file is rendered here: https://proto.school/#/regular-files-api/07

Fix markdown codeblock rendering issue

---

src/utils/tutorials.js

@zebateira A couple of folks used the new Twitter feature recently but I clicked through on the links and reached a 404 because the hash was missing in the URL. Feel free to merge if you agree that this little tweak fixes the issue. 
Interestingly hitting a GitHub-generated 404 and not our own - will this case be fixed by the routing PR you have in progress by any chance?

Fix tutorial URLs

---

src/tutorials/0005/05.vue
src/utils/ipfs.js

If js-ipfs fails with ERR_MORE_THAN_ONE_ROOT we can show a better message to the user.
Also added a new file `utils/ipfs.js` with an object of errors that we can use to check the errors from js-ipfs.
closes #357

fix: detect 'ERR_MORE_THAN_ONE_ROOT' error from js-ipfs

---

.github/ISSUE_TEMPLATE/lesson-feedback.md
.github/ISSUE_TEMPLATE/tutorial-feedback.md

Removing the sample URL because people keep leaving it there instead of filling in the section.

Remove sample URLs from issue template

---

src/components/Lesson.vue

This PR fixes the issue of when the resources lesson only gets marked as completed after you click the button "More Tutorials" at the end of the page.
For this we mark the lesson as completed when the page mounts
Closes #368

fix: mark resources "lesson" as passed on page mount

---

public/404.html

Closes #388 
This should fix the 404 gibhub page showing.
@terichadbourne what we discussed regarding redirecting valid urls to hash urls would be a bit more tricky (e.g. `/tutorials` -> `/#/tutorials`) since it would still rely on the 404 hack #393

fix: redirect any github 404 to our custom 404 page

---

src/tutorials/0006-anatomy-of-a-cid/01.md
src/tutorials/0006-anatomy-of-a-cid/05.md
src/tutorials/0006-anatomy-of-a-cid/06.md

As pointed out by @lidel, referencing the wikipedia snapshot as an example, it might not be a good idea in the tutorial because it might cause confusion about what the CID refers to (entire wikipedia snapshot or just that single wikipedia article).
To circumvent this issue, it's just easier to have an image as the content instead of a whole website.
Closes #401

fix(content): use an image instead of a website for the CID examples

---

src/tutorials/0006-anatomy-of-a-cid/01.js
src/tutorials/0006-anatomy-of-a-cid/02.js
src/tutorials/0006-anatomy-of-a-cid/03.js
src/tutorials/0006-anatomy-of-a-cid/04.js
src/tutorials/0006-anatomy-of-a-cid/05.js
src/tutorials/0006-anatomy-of-a-cid/06.js
src/tutorials/boilerplates/boilerplate-multiple-choice.js

@terichadbourne mentioned that having single quotes in the boilerplate makes it hard to write content because most of the times we'll need to use apostrophes, so let's switch them to double quotes and force this through file specific config.

fix: force double quotes on multiple choice files

---

src/components/callouts/TutorialCompletion.vue
src/static/projects.json

Closes #467 
This PR assigns `twitterHashtag` (used) and `twitterHandle` (where applicable, future-proofing) values in `projects.json`, then uses the `twitterHashtag` in place of `name` when building a proposed tweet from the `TutorialCompletion` component. This avoids the challenge we were having with our new psuedo-project "DWeb Concepts."

assign project hashtags and handles

---

.travis.yml
package-lock.json
package.json
scripts/commands/build-data/index.js
scripts/modules/googleapis/auth.js

If a build from a PR that is started from a forked project starts, travis does not allow the secure env vars to be used. See here: 
- Travis issues: [travis#701287172](https://travis-ci.org/github/ProtoSchool/protoschool.github.io/builds/701287172) [travis#701462759](https://travis-ci.org/github/ProtoSchool/protoschool.github.io/builds/701462759)
- this is because secure env vars are not available outside the repo
- [travis-ci#1946](https://github.com/travis-ci/travis-ci/issues/1946)
- [travis-ci#6611](https://github.com/travis-ci/travis-ci/issues/6611)
Documented here: [https://docs.travis-ci.com](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml)
> Encrypted environment variables are not available to pull requests from forks due to the …

Fix: handle PRs from forks failing builds

---

CODE_OF_CONDUCT.md
DESIGNING_TUTORIALS.md
DEVELOPING_TUTORIALS.md
src/tutorials/0004-mutable-file-system/09.md
src/tutorials/0004-mutable-file-system/10.md
src/tutorials/0006-anatomy-of-a-cid/02.md

Hey,
This PR will fix : 
- 1 typo in `CODE_OF_CONDUCT.md`
- 1 typo in `DESIGNING_TUTORIALS.md`
- 2 typos in `DEVELOPING_TUTORIALS.md`
- 1 typo in `src/tutorials/0004-mutable-file-system/09.md`
- 1 typo in `src/tutorials/0004-mutable-file-system/10.md`
- 1 typo in `src/tutorials/0006-anatomy-of-a-cid/02.md`
Bye! :robot:

docs: fix typos

---

src/static/tutorials.json
src/tutorials/0005-regular-files-api/03-challenge.md
src/tutorials/0005-regular-files-api/03.js
src/tutorials/0005-regular-files-api/03.md
src/tutorials/0005-regular-files-api/05-challenge.md
src/tutorials/0005-regular-files-api/05.js
src/tutorials/0005-regular-files-api/05.md
src/tutorials/0005-regular-files-api/06-challenge.md
src/tutorials/0005-regular-files-api/06.js
src/tutorials/0005-regular-files-api/06.md

The only affected tutorial is "Regular Files API". Affected lessons are lessons number 3, 5 and 6.

fix: lost references to the files.add method changed to files.addAll

---

DEVELOPING_TUTORIALS.md
src/tutorials/0001-data-structures/05.md
src/tutorials/0006-anatomy-of-a-cid/01.md
src/tutorials/0006-anatomy-of-a-cid/02.md
src/tutorials/0006-anatomy-of-a-cid/03.md
src/tutorials/0006-anatomy-of-a-cid/04.md
src/tutorials/0006-anatomy-of-a-cid/05.md
src/tutorials/0006-anatomy-of-a-cid/06.md

Images are not loading in the new netlify build: https://protoschool-prod.netlify.app/data-structures/05
The paths to the images need to be absolute.

fix: paths to images should be absolute, not relative

---

cypress/integration/redirects.spec.js

We need to remove them otherwise the tests might fail on local machines, but work on CI, even though we are not testing against the correct server.

fix: remove 404 tests because they are testing server functionality

---

cypress/integration/tutorials.spec.js
src/components/Lesson.vue
src/utils/tutorials.js

Fixes #530
Any new progress with the trailing slash will not be taken into account, but previous progress without the slash will still be taken into account. I don't think this will be a problem since advancing any lesson was working, so effectively, no progress will be lost, but I thought I'd still mention it.

fix: do not use trailing slashes in local storage item ids

---

cypress/integration/tutorials.spec.js

Just a small change to the tests to use the already created `testLessons` data.

fix: use testLessons data for new tests as well

---

src/pages/Build.vue
src/pages/Contribute.vue
src/pages/Events.vue
src/pages/Home.vue
src/pages/Host.vue
src/pages/News.vue
src/pages/Tutorials.vue
src/utils/head/index.js

`head` was not being called on every page change.
Change on some pages from
```js
head: head()
```
to 
```js
head() {
return head()
}
Closes #526

fix: document metadata was not updating between some pages

---

src/utils/head/data/dynamic-pages.js

Updates page titles to emphasize "<Project> Tutorial" over the tutorial title and the tutorial title over the lesson number (where relevant), so as to make it easier for users reading through search results to find what they're looking for.

update lesson and tutorial page titles

---

cypress/integration/redirects.spec.js
src/router.js
src/routes.js

I noticed that in countly we were getting a lot of data points with inconsistent urls that include trailing slashes and others that don't.
Examples:
- Events: https://countly.proto.school/dashboard#/5d25fd49db14b4435e4432e2/analytics/events/key/tutorialFeedbackSurveyCompleted
- Page Views (notice the `/data-structures` url has a duplicated entry with `/data-structures/`
This PR will remove the trailing slash on client-slide. Netlify/Fleek trailing slash redirect will not be affected and will still happen.
By using `vue-router`'s `beforeEach` function, we can remove the trailing slash from window location if it's present, and only the client side will be affected.
So the redirect from Netlify/Fleek to add the trailing slash will still happen, but then `vue-router` kicks in and will remove …

fix: remove trailing slash on vue router to make countly data consistent

---

src/router.js

With the latest fix, we are now removing the trailing slash, but also removing the query parameters.
Example: https://proto.school/tutorials/?code=true&course=ipfs would redirect to https://proto.school/tutorials
This PR fixes this. Keeps the redirect that removes the trailing slash, keeping the query parameters if present.

fix: add query to trailing slash removal logic

---

src/router.js

When a user comes back to a tab with ProtoSchool open after a deployment, they might get this ChunkLoadError error because the chunk's name does not exist anymore (because of cache busting hashes in the filenames).
The fix for this is to force the browser to reload.
In addition to that, we are navigating the user to the route they wanted to change to, so that instead of simply reloading the page, the user actually navigates to the correct page.
Closes #555 
- https://dev.to/ianwalter/fixing-chunkloaderror-3791
1. run prod build and server it: `npm run build && npm run cy:serve`
2. open localhost:3000 without cache enabled (dev tools > network > disable cache: on)
3. change content in the Events page. Open `src/pages/Events.vue` file, and change the content (add `test` anywhere in the …

fix: force page refresh on ChunkLoadError

---

cypress/integration/tutorials.spec.js
cypress/plugins/index.js
package-lock.json
package.json

This PR upgrades Cypress to version 5.
I'll make a separate PR to add testing on other browsers on CI (Fleek) because we might need to update the docker image we are using to include the other browsers. So this only addresses #386 partially.
Refs:
- [Cypress Migration Guide](https://docs.cypress.io/guides/references/migration-guide.html#Mocha-upgrade)

Chore: Upgrade Cypress to version 5

---

src/App.vue

ATM the content is not occupying the full viewport and the footer on the lesson pages does not stick to the bottom of the viewport on larger screens:
To fix this I adapted the layout styles from [next-with-moxy](https://github.com/moxystudio/next-with-moxy) to fix this issue thoroughly across browsers and devices.
Adapted from https://github.com/moxystudio/next-with-moxy/blob/master/www/shared/styles/global/layout.css

fix: make sure the document, body and its children adapt to the viewport in height

---

src/components/Tutorial.vue

fix: move tutorial completed badge (trophy) to the top

---

src/components/Lesson.vue
src/components/Output.vue
src/components/Validator.vue

Addresses #596 partially.
Syntax errors were not being given as feedback in the `Output` component on a specific case.
Although, the monaco editor should show the syntax error feedback right from the start to avoid situations like these #596 where the user simply missed a comma.
Fixing the code editor is filed here: https://github.com/ProtoSchool/protoschool.github.io/issues/597
This PR only addresses the issue of no error feedback when submitting code with a syntax error.

fix: show syntax error

---

cypress.json
cypress/integration/tutorial-redirect-modal.spec.js
package-lock.json
package.json
src/App.vue
src/api/debug.js
src/api/modules/lessons.js
src/api/modules/resources.js
src/api/modules/tutorials.js
src/components/Lesson.vue
src/components/buttons/Button.vue
src/components/buttons/ButtonClose.vue
src/components/buttons/ButtonLink.vue
src/components/modals/BaseModal.vue
src/components/modals/TutorialRedirectModal.vue
src/config.js
src/main.js
src/pages/Home.vue
src/pages/Lesson.vue
src/routes.js
src/state/init.js
src/state/modals.js
src/static/translations/en.json
src/styles/media-queries.css
src/utils/countly.js
src/utils/debug.js
src/utils/env.js
src/utils/tutorials.js

This modal should appear only to users that land on a lesson page from a search engine result, mostly.
The logic for this is as follow:
```js
typeof document !== 'undefined' && // not available in prerender
document.referrer &&
tutorialRedirectModal.referrer.SEARCH_ENGINES.some(searchEngine => document.referrer.includes(searchEngine.url)) && // if the user came from a search engine
this.lesson.id !== 1 &&
this.lesson.type !== 'resources' &&
!isLessonPassed(this.tutorial, this.lesson)
```
Breaking it down:
1. `typeof document !== 'undefined' && // not available in prerender`
Don't prerender the pages with the modal
2. `tutorialRedirectModal.referrer.SEARCH_ENGINES.some(searchEngine => document.referrer.includes(searchEngine.url))`
The [document …

feat: add tutorial redirect modal

---

package-lock.json
package.json

I wasn't able to build the project when first checking this repo out. I'm running on an M1 MacBook Air running Big Sur (version 11.1). 
I think this error is related to old versions of some dependencies being pinned in `package-lock.json` and forcing an old version of `node-gyp`, which fails on recent builds of Mac OS.
I was able to regenerate the `package-lock.json` without updating any dependencies in `package.json`, and now the build succeeds. The `bcrypto` package that was failing to build on the main branch isn't even pulled in anymore, so one of our transitive dependencies must have updated.
Hopefully closes #576

fix macos build: update ipfs dependency to v0.50.2

---

src/tutorials/0005-regular-files-api/06.md

The examples are using the MFS API, not the regular files API. This change switches them to the regular files API

Use Regular File API in examples

---

src/tutorials/0004-mutable-file-system/02.md

Before: https://proto.school/mutable-file-system/02
After: https://bafybeigycb6u73t2hp7is7cuvabltbsovkf3yordcvzy27pisgjmctd6tq.on.fleek.co/mutable-file-system/02

fix: code block in mfs lesson 2 badly formatted

---

src/config.js
src/utils/tutorials.js

This PR sets a fixed domain to be used in tweets rather than using data from the window (could be localhost, IPFS links, etc.), which had previously led to tweets with non-functional links such as:

set fixed domain for tweets
