- src/components/Home.vue
- src/lessons/Pw/01.md
- src/lessons/Pw/01.vue
- src/lessons/Pw/02.md
- src/lessons/Pw/02.vue
- src/lessons/Pw/03.md
- src/lessons/Pw/03.vue
- src/lessons/Pw/04.md
- src/lessons/Pw/04.vue
- src/lessons/Pw/05.md
- src/lessons/Pw/05.vue
- src/lessons/Pw/06.md
- src/lessons/Pw/06.vue
- src/main.js
The lessons start at `/#/11` and go up to `/#/16`.
This [robably only make sense with the DAG being displayed (as it is mostly about links). I push it, so that we can discuss if it makes sense to polish or abandon it.
The lessons work, just details (like the image) is missing. So feel free to follow along.
It's not that much about coding, it's rather about building up a DAG. I had this idea before we had the workshopper tool as a real thing.
> Add lessons about the permanent Web

- package-lock.json
- package.json
- src/components/home/Home.vue
- src/lessons/Blog/01.md
- src/lessons/Blog/01.vue
- src/lessons/Blog/02.md
- src/lessons/Blog/02.vue
- src/lessons/Blog/03.md
- src/lessons/Blog/03.vue
- src/lessons/Blog/04.md
- src/lessons/Blog/04.vue
- src/lessons/Blog/05.md
- src/lessons/Blog/05.vue
- src/lessons/Blog/06.md
- src/lessons/Blog/06.vue
- src/lessons/Blog/07.md
- src/lessons/Blog/07.vue
- src/lessons/Blog/utils.js
- src/main.js
Notes:
- Currently the pre-populated code is the solution of the previous
lesson. So you can e.g. copy the code from lesson 3 into the code
box of lesson 2 and it should validate correctly.
- Validations for lesson 1-5 is done
- Validations for other lessons is missing
- I'm still unclear on how to validate lesson 6
@olizilla Here's the PR, just for you!
> WIP: blog lessons

- src/components/home/Home.vue
- src/lessons/Blog/01.md
- src/lessons/Blog/02.md
- src/lessons/Blog/02.vue
- src/lessons/Blog/03.md
- src/lessons/Blog/03.vue
- src/lessons/Blog/04.md
- src/lessons/Blog/04.vue
- src/lessons/Blog/05.md
- src/lessons/Blog/05.vue
- src/lessons/Blog/06.md
- src/lessons/Blog/06.vue
- src/lessons/Blog/07.vue
Here are better descriptions for lessons 1-3. Those lessons slowly feel better and better to me.
Feedback is welcome. I will do the other 4 descriptions later tonight.
> WIP: Blog lessons descriptions

- src/lessons/Blog/07.md
I think I've incorporated all notes @olizilla had in #14.
> fix: better description for blog lesson 7

- src/lessons/Blog/01.md
- src/lessons/Blog/02.md
- src/lessons/Blog/03.md
- src/lessons/Blog/04.md
- src/lessons/Blog/05.md
- src/lessons/Blog/06.md
- src/lessons/Blog/07.md
Here are copy edits to all the blog lessons.
> fix: copy edits on the blog lesson.

- src/main.js
as per https://router.vuejs.org/guide/advanced/scroll-behavior.html
Fixes #30 
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
> feat: reset page scroll pos when changing route

- .github/weekly-digest.yml
Trying out the automated weekly digest https://github.com/probot/weekly-digest
> Configure weekly-digest automation.

- src/components/home/Home.vue
> fix a typo

- src/components/home/Home.vue
- src/lessons/Basics/01-concepts.md
- src/lessons/Basics/01-exercise.md
- src/lessons/Basics/01.md
- src/lessons/Basics/01.vue
- src/lessons/Basics/02-concepts.md
- src/lessons/Basics/02-exercise.md
- src/lessons/Basics/02.md
- src/lessons/Basics/02.vue
- src/lessons/Basics/03.vue
- src/lessons/Blog/01-exercise.md
- src/lessons/Blog/01.md
- src/lessons/Blog/02-exercise.md
- src/lessons/Blog/02.md
- src/lessons/Blog/03.md
- src/lessons/Blog/04-exercise.md
- src/lessons/Blog/05-exercise.md
- src/lessons/Blog/06-exercise.md
- src/lessons/Blog/06.md
- src/lessons/Blog/07.md
- Edits to improve grammar and make formatting consistent
- Add concepts box to 1st basics lesson and explain that the `ipfs.dag.put` function returns a CID
> Grammar and formatting edits

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/lesson-feedback.md
- .github/ISSUE_TEMPLATE/workshop-proposal.md
Add issue templates for lesson feedback and new workshop proposals
> Update issue templates

- src/components/chapters/chapters.json
- src/components/home/Home.vue
- Remove the dummy data (extra chapters and tutorials) that had been
used to test site design
> Remove dummy data

- src/lessons/Data-Structures/01.md
(Or, we could carry over the footnotes.)
> Remove footnote markers from Wikipedia quote

- package-lock.json
- package.json
- Change package name and bump version
> Rename package to protoschool and bump to 1.0.0

- src/components/chapters/chapters.json
> Update chapters.json for Hong Kong Chapter

- src/components/Lesson.vue
This PR lazy loads the IPFS module in the lesson component. This should result in a significantly smaller bundle size for the index page of the site.
> feat: code split ipfs module using import()

- src/components/chapters/chapters.json
Update chapters.json on protoschool.github.io repo, following
step 5 of Organizing under README.md of
https://github.com/ProtoSchool/organizing#how-to-start-a-new-protoschool-chapter
> Add Seattle chapter to ProtoSchool

- src/components/chapters/chapters.json
Update chapters.json on protoschool.github.io repo, following
step 5 of Organizing under README.md of
https://github.com/ProtoSchool/organizing#how-to-start-a-new-protoschool-chapter
@ProtoSchool/beijing
> add protoschool/beijing chapter config json

- src/components/chapters/chapters.json
Added Washington-DC chapter info
> Added Washington DC to chapters.json

- src/components/chapters/chapters.json
This PR includes the following changes:
- Format the `chapter.json` file with [RFC 4627](https://www.ietf.org/rfc/rfc4627.txt?number=4627) JSON standard
- Group all chapters by region
- Sort regional chapters by city name in alphabetical order
- Add a new chapter - **Shanghai**
PTAL @terichadbourne 
/cc @steven004
> feat(chapter): set up shanghai chapter and format code

- src/components/Build.vue
Fix broken links to new-tutorial issues
> Fix broken links to new-tutorial issues

- src/components/chapters/chapters.json
Applying 2-digit country code for consistency with other entries.
> Change "Germany" to "DE"

- src/components/chapters/chapters.json
> Add Berlin chapter

- src/components/chapters/chapters.json
Fixes https://github.com/ProtoSchool/organizing/issues/35
> Adding Bangalore chapter, Yay!

- src/components/chapters/chapters.json
Closes https://github.com/ProtoSchool/lisbon/issues/3!
/cc @terichadbourne
> Add Lisbon to Chapters

- src/components/chapters/chapters.json
Welcome Kelsey to Seattle chapter organzing team! 🎉
> Add Kelsey Breseman as an organizer

- src/components/Build.vue
- src/components/Contribute.vue
- src/components/Lesson.vue
- src/components/Navigation.vue
- src/main.js
Reduces the number of errors that show up when running `npm run serve` for a nicer contributor experience.
> Fixed some eslint errors

- public/index.html
Add Google verification meta tag
> Add Google verification meta tag

- src/tutorials/Basics/01-exercise.md
- src/tutorials/Basics/01.md
- src/tutorials/Basics/02.md
Fixes https://github.com/ProtoSchool/protoschool.github.io/issues/183.
> fix: clarify info of Basics - Lesson 2

- src/components/Navigation.vue
Multiple times I've found myself wanting to click the marked link to go to the tutorial landing page, but that wasn't a link.
✅ It is now!
> chore: add navbar link to landing

- src/tutorials/Blog/01.vue
- src/tutorials/Blog/02.md
- src/tutorials/Blog/02.vue
- src/tutorials/Blog/03-exercise.md
- src/tutorials/Blog/03.md
- src/tutorials/Blog/03.vue
- src/tutorials/Blog/04.vue
- src/tutorials/Blog/05.vue
- src/tutorials/Blog/06.vue
- src/tutorials/Blog/07.md
- src/tutorials/Blog/07.vue
- src/tutorials/Blog/utils.js
- src/tutorials/Data-Structures/04.md
Add UI logs to blog tutorial and rephrased some lessons to make them clearer.
> feat: add ui logs to blog tutorial

- README.md
- src/components/Lesson.vue
> feat: enable markdown formatting of logDesc

- README.md
Just some minor spelling fixes for the readme.
> docs: fix language in the readme

- src/static/chapters.json
> add chengdu chapter

- src/components/Lesson.vue
Fixes https://github.com/ProtoSchool/protoschool.github.io/issues/232.
> fix: break-word in output logs

- src/static/chapters.json
For this issue : https://github.com/ProtoSchool/beijing/issues/9
> Remove chapter organizer of ProtoSchool Beijing

- src/tutorials/Basics/03-exercise.md
- src/tutorials/Basics/03.md
- src/tutorials/Basics/03.vue
Closes #209 & #210, addressing feedback received submitted by @frijol and @ajhurliman from the Seattle chapter. I'd love your feedback on whether this addresses your concerns.
> clarify how to access value property (basics #3)

- src/components/LessonLink.vue
Closes https://github.com/ProtoSchool/protoschool.github.io/issues/245.
> fix: mobile icon sizes

- public/index.html
Closes https://github.com/ProtoSchool/protoschool.github.io/issues/247.
> chore: remove IPFS Camp banner

- src/components/LessonLink.vue
Fixes https://github.com/ProtoSchool/protoschool.github.io/issues/245.
> fix: mobile icons

- src/pages/Contribute.vue
> Fix mailto link

- .travis.yml
- src/App.vue
- src/components/Breadcrumbs.vue
- src/components/Button.vue
- src/components/CodeEditor.vue
- src/components/Concepts.vue
- src/components/FileLesson.vue
- src/components/FileUpload.vue
- src/components/Info.vue
- src/components/Landing.vue
- src/components/Lesson.vue
- src/components/Output.vue
- src/components/Progress.vue
- src/components/Validator.vue
- src/pages/Chapters.vue
- src/pages/Tutorials.vue
- src/tutorials/Blog/02.md
- src/tutorials/Blog/02.vue
- src/tutorials/Mutable-File-System/02.vue
- src/tutorials/Mutable-File-System/03.vue
- src/tutorials/Mutable-File-System/04.vue
- src/tutorials/Mutable-File-System/05.vue
- src/tutorials/Mutable-File-System/06.vue
- src/tutorials/Mutable-File-System/07.vue
- src/tutorials/Mutable-File-System/08.vue
- src/tutorials/Mutable-File-System/09.vue
- src/tutorials/Mutable-File-System/10.vue
- src/tutorials/Mutable-File-System/11.vue
- src/tutorials/boilerplates/boilerplate-file-upload.vue
> chore: refactor lesson component

- src/App.vue
Fixes https://github.com/ProtoSchool/protoschool.github.io/issues/278.
> fix: unneeded scrollbars

- src/tutorials/Mutable-File-System/02.md
Thanks to @doctorrobinson for catching this broken link!
> Fix broken link to install instructions

- src/components/Breadcrumbs.vue
- src/components/Lesson.vue
- src/components/Navigation.vue
- src/components/Validator.vue
- src/pages/Tutorials.vue
Fixes https://github.com/ProtoSchool/protoschool.github.io/issues/284.
> fix: reword workshop to tutorial

- src/components/Navigation.vue
Adds a bit of padding to the navbar hamburguer icon to increase its touch area in mobile.
Closes https://github.com/ProtoSchool/protoschool.github.io/issues/128.
> chore: add navbar padding

- src/tutorials/0004/10.vue
There was a missing `await`, which I believe was not on purpose.
> Missing await in the exercise 10 code (Mutable File System)

- src/static/chapters.json
@terichadbourne finally made Tokyo chapter!
> adding Tokyo chapter to chapters.json

- src/components/FileLesson.vue
- src/components/FileUpload.vue
Possibly fixes issue #230. Should maybe verify again after finding a consistent way to replicate the bug.
> fix: fix bug where choosing a file to upload does not select any file

- src/pages/Build.vue
- src/pages/Contribute.vue
- src/pages/Host.vue
Updates to Contribute, Host, and Build page to better describe ways to contribute to the project and emphasize that coding skills aren't required.
> Updates to contributor info

- .editorconfig
> chore: add editor config file

- src/tutorials/0001-data-structures/03.md
- src/tutorials/0004-mutable-file-system/05.md
> fix(content): cryptographic typo

- .gitignore
@zebateira Just a quick edit to protect ourselves from accidentally  merging into `code` the `.env` file we're each working with locally in another branch.
> Update .gitignore approach to .env files

- src/tutorials/0005-regular-files-api/01.md
- src/tutorials/0005-regular-files-api/03.md
Closes #404, #406 
Thank you @AlohaCode!
> fix(content): a typo and better clarity for a sentence

- .travis.yml
- package-lock.json
- package.json
- scripts/README.md
- scripts/commands/build-data/events-data.js
- scripts/commands/build-data/index.js
- scripts/commands/build-data/mailchimp.js
- scripts/modules/data/events.js
- scripts/modules/googleapis/auth.js
- scripts/modules/mailchimp/auth.js
- scripts/modules/mailchimp/index.js
- scripts/modules/mailchimp/lists.js
- scripts/modules/mailchimp/request.js
- scripts/modules/run.js
- src/static/events.json
Add Mailchimp integration: if an event organizer is not on the Mailchimp Audience, add them.
TODO:
> Feature: Mailchimp integration

- src/tutorials/0001-data-structures/02.md
**Changes proposed:**
* Fix a minor typo kindess -> kindness
> Fix typo: kindess -> kindness

- src/static/chapters.json
Repo deleted by organizer so deleting corresponding entry
> Remove Berlin

- scripts/commands/wizard/utils.js
> fix: make new tutorial option standout from the list of tutorials

- src/tutorials/0007-verifying-storage-on-filecoin/03.md
- src/tutorials/0007-verifying-storage-on-filecoin/04.js
- src/tutorials/0007-verifying-storage-on-filecoin/04.md
- src/tutorials/0007-verifying-storage-on-filecoin/06.md
Closes #455 #454 
This PR aims to address the inaccuracies pointed out by @porcuquine in the Verifying Storage on Filecoin tutorial. Look forward to confirmation that this attempt at rephrasing is actually true while still being beginner-friendly. 
co-authored by @mishmosh
> Address inaccuracies in Verifying Storage on Filecoin 

- src/tutorials/0007-verifying-storage-on-filecoin/01.md
- src/tutorials/0007-verifying-storage-on-filecoin/04.js
- src/tutorials/0007-verifying-storage-on-filecoin/06.md
Correct the errors we've been reading past a gazillion times without noticing them.  🤦‍♀️
> correct Proof of Spacetime references

- src/tutorials/0007-verifying-storage-on-filecoin/02.md
Closes #481 by explaining bit padding
> Explain bit padding

- cypress.json
- cypress/integration/tutorials.spec.js
- package-lock.json
- package.json
- src/components/Lesson.vue
- src/utils/env.js
This is a short term solution I found to make the tests pass in Travis: increase the timeouts.
The reason why some tests fail seems to be because submitting the code solution takes some time. up to 30 seconds sometimes, but it can spike further - 60s timeout was not enough in some rare occasions.
So it seems that some ipfs operations are taking longer than desirable. I'm not sure why this is the case only in travis. Locally (and production) it's not that slow, but I was able to reproduce it running on electron locally.
> Fix: tests failing on travis

- src/components/CodeEditor.vue
- src/components/Lesson.vue
- src/components/Output.vue
- src/utils/countly.js
> Tracking: add new CODE_VIEW_SOLUTION and SUCCESS_LINK_CLICK countly events

- src/pages/News.vue
- src/static/projects.json
- src/utils/countly.js
- src/utils/projects.js
See cross-promotion design issue: https://github.com/protocol/design-shop/issues/333
> Add links to related newsletters

- public/index.html
Incorporate top content areas into description in site meta tags. Will await a little feedback here or in Slack before merging. https://protocollabs.slack.com/archives/C1C26KDR9/p1595352548179000
> chore: update site description

- src/static/tutorials.json
> fix: resources link to youtube video is lower cased

- src/tutorials/0007-verifying-storage-on-filecoin/06.md
> Content: align table results in Lesson 6

- src/main.js
- src/routes.js
- src/utils/head/data/root.js
- vue.config.js
Removes the additional renderAfterElementExists to remove ambiguity.
closes #517
> fix: prevent render before vue app has mounted

- public/ipfs-404.html
Addresses missing 404 handler in #524
> feat: add ipfs-404.html file to add 404 handler to fleek

- README.md
Update list of URLs from which you can test Countly without affecting our stats
> Update list of testing URLs

- src/components/Quiz.vue
> fix: positioning of radio button selected state

- src/pages/News.vue
> fix: use new Project Icon component

- src/static/tutorials.json
After doing a review for dating on the new version of the IPFS blog, I'm updating historical publication dates here. Haven't changed any updated dates. @zebateira feel free to merge unless you can envision any unintended side effects of these changes.
> Correct original publication dates

- cypress/integration/footer.spec.js
- src/App.vue
- src/components/Lesson.vue
- src/components/layout/Footer.vue
- src/components/layout/Header.vue
- src/components/layout/Navigation.vue
- src/pages/Build.vue
- src/pages/Contribute.vue
- src/pages/Course.vue
- src/pages/Events.vue
- src/pages/Home.vue
- src/pages/Host.vue
- src/pages/Landing.vue
- src/pages/News.vue
- src/pages/NotFound.vue
- src/pages/Tutorials.vue
- src/router.js
- src/static/translations/en.json
WIP - will close #515 by adding footer (both for IA and SEO purposes) 
Note that the callout that looked like a navy footer requesting feedback on specific lessons has been changed to aqua so it can be used in combo with this new universal footer where needed...
This needs more styling work and more discussion about what content to include, including... 
**Styling improvements needed**
**Content decisions to discuss**
**Bugs**
**Other**
@zebateira Please feel free to add any other concerns/questions to the list above. I know you have some styling suggestions in mind... why don't you jot those down here and I can tackle or we can work together during a pairing session so I get the experience making CSS bend to my will.
> Add footer

- src/tutorials/0001-content-addressing/01.md
> Larry --> Lars

- src/pages/Home.vue
The [ResNetLab on Tour](https://research.protocol.ai/tutorials/resnetlab-on-tour/) series of video tutorials are a great educational resource for the community and ties very well with the ProtoSchool materials. This PR links to RNLoT from the bottom of the ProtoSchool landing page.
> Linking ResNetLab on Tour Video Tutorials
